# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c9ef8c702e762d77ae0dc2caba31afa50acf0b5cff78ba48e87bbeafdaa75fc6dc754480a6a57a66d4bb0fb3717c57804c4fe71b067b740236c68901744764

test:
  secret_key_base: e04dde01e88aaddced6dff50a1e7e94272d44e42ad45422131ad7d24688127b5403153e4bf79f10a8bf42fef8009d08116eb48288d7d9e1322178adefcebe14e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
